{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "74Gxd2JA8SVO"
      },
      "outputs": [],
      "source": [
        "!pip install streamlit -q"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!wget -q -O - ipv4.icanhazip.com"
      ],
      "metadata": {
        "id": "4qtDNNhp8Wyo"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile DecisionTree_app.py"
      ],
      "metadata": {
        "id": "HPT1exVR8dPh"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!npm install localtunnel"
      ],
      "metadata": {
        "id": "3m-kiy-n8gBe"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!streamlit run DecisionTree_app.py &npx localtunnel --port 8501"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "bGBzRF5V8nFh",
        "outputId": "8a36b36c-bcff-469a-bd85-017833e78613"
      },
      "execution_count": null,
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\n",
            "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.\n",
            "\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m  Local URL: \u001b[0m\u001b[1mhttp://localhost:8501\u001b[0m\n",
            "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.28.0.12:8501\u001b[0m\n",
            "\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://34.29.93.195:8501\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[K\u001b[?25hnpx: installed 22 in 2.047s\n",
            "your url is: https://silly-wombats-sleep.loca.lt\n",
            "2024-07-02 10:23:21.645 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 4, in <module>\n",
            "    model = pickle.load(open('model.pkl','rb'))\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'\n",
            "2024-07-02 10:25:51.797 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 4, in <module>\n",
            "    model = pickle.load(open('model.pkl','rb'))\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'\n",
            "2024-07-02 10:26:14.082 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 4, in <module>\n",
            "    model = pickle.load(open('model.pkl','rb'))\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'\n",
            "2024-07-02 10:55:59.346 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 38, in <module>\n",
            "    main()\n",
            "  File \"/content/DecisionTree_app.py\", line 33, in main\n",
            "    diagnosis = diabetes_prediction([Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age])\n",
            "  File \"/content/DecisionTree_app.py\", line 7, in diabetes_prediction\n",
            "    input_data = np.asarray(input_data)\n",
            "ValueError: invalid __array_struct__\n",
            "2024-07-02 10:59:23.111 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 38, in <module>\n",
            "    main()\n",
            "  File \"/content/DecisionTree_app.py\", line 33, in main\n",
            "    diagnosis = diabetes_prediction([Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age])\n",
            "  File \"/content/DecisionTree_app.py\", line 7, in diabetes_prediction\n",
            "    input_datas = np.asarray(input_data)\n",
            "ValueError: invalid __array_struct__\n",
            "2024-07-02 11:13:53.637 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 48, in <module>\n",
            "    st.scatter(b,c)\n",
            "AttributeError: module 'streamlit' has no attribute 'scatter'\n",
            "2024-07-02 11:14:33.010 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 48, in <module>\n",
            "    st. plotly_chart(b,c)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 408, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/plotly_chart.py\", line 480, in plotly_chart\n",
            "    figure = plotly.tools.return_figure_from_figure_or_data(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/tools.py\", line 543, in return_figure_from_figure_or_data\n",
            "    raise exceptions.PlotlyError(\n",
            "_plotly_utils.exceptions.PlotlyError: The `figure_or_data` positional argument must be `dict`-like, `list`-like, or an instance of plotly.graph_objs.Figure\n",
            "2024-07-02 11:14:43.468 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 48, in <module>\n",
            "    st.plotly_chart(b,c)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 408, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/plotly_chart.py\", line 480, in plotly_chart\n",
            "    figure = plotly.tools.return_figure_from_figure_or_data(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/tools.py\", line 543, in return_figure_from_figure_or_data\n",
            "    raise exceptions.PlotlyError(\n",
            "_plotly_utils.exceptions.PlotlyError: The `figure_or_data` positional argument must be `dict`-like, `list`-like, or an instance of plotly.graph_objs.Figure\n",
            "2024-07-02 11:15:53.046 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 48, in <module>\n",
            "    st.plotly_chart(b,c)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 408, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/plotly_chart.py\", line 480, in plotly_chart\n",
            "    figure = plotly.tools.return_figure_from_figure_or_data(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/tools.py\", line 543, in return_figure_from_figure_or_data\n",
            "    raise exceptions.PlotlyError(\n",
            "_plotly_utils.exceptions.PlotlyError: The `figure_or_data` positional argument must be `dict`-like, `list`-like, or an instance of plotly.graph_objs.Figure\n",
            "2024-07-02 11:16:29.134 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 48, in <module>\n",
            "    fig = px.scatter(df, x='b', y='c', size='size', color='color')\n",
            "NameError: name 'px' is not defined\n",
            "2024-07-02 11:16:46.187 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 48, in <module>\n",
            "    fig = pd.scatter(df, x='b', y='c', size='size', color='color')\n",
            "AttributeError: module 'pandas' has no attribute 'scatter'\n",
            "2024-07-02 11:17:41.883 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 49, in <module>\n",
            "    fig = px.scatter(df, x='b', y='c', size='size', color='color',\n",
            "NameError: name 'px' is not defined\n",
            "2024-07-02 11:18:02.777 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 50, in <module>\n",
            "    fig = px.scatter(df, x='b', y='c', size='size', color='color',\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 66, in scatter\n",
            "    return make_figure(args=locals(), constructor=go.Scatter)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'] but received: b\n",
            "2024-07-02 11:18:29.303 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 49, in <module>\n",
            "    fig = px.scatter(df, x='b', y='c', size='size', color='color',\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_chart_types.py\", line 66, in scatter\n",
            "    return make_figure(args=locals(), constructor=go.Scatter)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 2003, in make_figure\n",
            "    args = build_dataframe(args, constructor)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1412, in build_dataframe\n",
            "    df_output, wide_id_vars = process_args_into_dataframe(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/plotly/express/_core.py\", line 1208, in process_args_into_dataframe\n",
            "    raise ValueError(err_msg)\n",
            "ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'] but received: b\n",
            "2024-07-02 11:22:11.865 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 50, in <module>\n",
            "    st.line_chart(a,c)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 408, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "TypeError: VegaChartsMixin.line_chart() takes from 1 to 2 positional arguments but 3 were given\n",
            "2024-07-02 11:22:42.078 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 50, in <module>\n",
            "    st.scatter_chart(a,c)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 408, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "TypeError: VegaChartsMixin.scatter_chart() takes from 1 to 2 positional arguments but 3 were given\n",
            "2024-07-02 11:22:47.782 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 50, in <module>\n",
            "    st.scatter_chart(a,c)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 408, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "TypeError: VegaChartsMixin.scatter_chart() takes from 1 to 2 positional arguments but 3 were given\n",
            "2024-07-02 11:23:21.317 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 50, in <module>\n",
            "    st.scatter_chart(a,c)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 408, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "TypeError: VegaChartsMixin.scatter_chart() takes from 1 to 2 positional arguments but 3 were given\n",
            "2024-07-02 11:24:18.217 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 50, in <module>\n",
            "    st.scatter_chart(df[\"Age\"],df[\"BMI\"])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 408, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "TypeError: VegaChartsMixin.scatter_chart() takes from 1 to 2 positional arguments but 3 were given\n",
            "2024-07-02 11:30:27.514 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 57, in <module>\n",
            "    st.hist_frame(a)\n",
            "AttributeError: module 'streamlit' has no attribute 'hist_frame'\n",
            "2024-07-02 11:30:57.273 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 589, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/DecisionTree_app.py\", line 57, in <module>\n",
            "    st.hist_chart(a)\n",
            "AttributeError: module 'streamlit' has no attribute 'hist_chart'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "dLxoxP-P9GlN"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}